"""auto-generated

Revision ID: af6b6c68da87
Revises: 6831398101c6
Create Date: 2026-04-27 09:33:04.694077
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'af6b6c68da87'
down_revision: Union[str, None] = '6831398101c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huddle_participants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('huddle_participants', 'role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('huddles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('notifications', 'kind',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'kind',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('huddles', 'created_at')
    op.alter_column('huddle_participants', 'role',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_column('huddle_participants', 'created_at')
    # ### end Alembic commands ###
