"""initial_schema

Revision ID: ba3365dfe1df
Revises: 
Create Date: 2026-04-21 22:26:25.316969
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ba3365dfe1df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('registered_at', sa.BigInteger(), nullable=False),
    sa.Column('registered_by', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_workspace_id'), 'agents', ['workspace_id'], unique=False)
    op.create_table('attachments',
    sa.Column('file_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('thumbnail_key', sa.Text(), nullable=True),
    sa.Column('virus_scan_status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_attachments_workspace_id'), 'attachments', ['workspace_id'], unique=False)
    op.create_table('channel_members',
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'user_id', name='ux_channel_members_cid_uid')
    )
    op.create_index(op.f('ix_channel_members_channel_id'), 'channel_members', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_members_user_id'), 'channel_members', ['user_id'], unique=False)
    op.create_table('channels',
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('staging_policy', sa.String(length=255), nullable=False),
    sa.Column('slow_mode_seconds', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_index(op.f('ix_channels_workspace_id'), 'channels', ['workspace_id'], unique=False)
    op.create_table('drafts',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('thread_root', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='ux_drafts_uid_cid')
    )
    op.create_index(op.f('ix_drafts_channel_id'), 'drafts', ['channel_id'], unique=False)
    op.create_index(op.f('ix_drafts_user_id'), 'drafts', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('room_id', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.Text(), nullable=False),
    sa.Column('sender_type', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('origin_ts', sa.BigInteger(), nullable=False),
    sa.Column('relates_to_id', sa.Text(), nullable=True),
    sa.Column('relates_to_rel', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('origin', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('workspace_id', 'sequence', name='ux_events_workspace_seq')
    )
    op.create_index(op.f('ix_events_sequence'), 'events', ['sequence'], unique=False)
    op.create_index(op.f('ix_events_workspace_id'), 'events', ['workspace_id'], unique=False)
    op.create_table('hof_flow_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flow_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flow_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hof_flow_executions_flow_name'), 'hof_flow_executions', ['flow_name'], unique=False)
    op.create_index(op.f('ix_hof_flow_executions_status'), 'hof_flow_executions', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('thread_root', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.Text(), nullable=False),
    sa.Column('sender_type', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edited_at', sa.BigInteger(), nullable=True),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('redact_reason', sa.Text(), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('imported_from', sa.Text(), nullable=True),
    sa.Column('original_author', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_sequence'), 'messages', ['sequence'], unique=False)
    op.create_index(op.f('ix_messages_thread_root'), 'messages', ['thread_root'], unique=False)
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_table('pinned',
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('pinned_at', sa.BigInteger(), nullable=False),
    sa.Column('pinned_by', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='ux_pinned_cid_mid')
    )
    op.create_index(op.f('ix_pinned_channel_id'), 'pinned', ['channel_id'], unique=False)
    op.create_table('proposals',
    sa.Column('proposal_id', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=True),
    sa.Column('command_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('resolved_at', sa.BigInteger(), nullable=True),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('edited_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proposal_id')
    )
    op.create_index(op.f('ix_proposals_channel_id'), 'proposals', ['channel_id'], unique=False)
    op.create_index(op.f('ix_proposals_workspace_id'), 'proposals', ['workspace_id'], unique=False)
    op.create_table('reactions',
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('emoji', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('added_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'emoji', 'user_id', name='ux_reactions_mid_emoji_uid')
    )
    op.create_index(op.f('ix_reactions_message_id'), 'reactions', ['message_id'], unique=False)
    op.create_table('read_markers',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.Text(), nullable=False),
    sa.Column('up_to_sequence', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='ux_read_markers_uid_cid')
    )
    op.create_index(op.f('ix_read_markers_channel_id'), 'read_markers', ['channel_id'], unique=False)
    op.create_index(op.f('ix_read_markers_user_id'), 'read_markers', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('joined_at', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='ux_workspace_members_wid_uid')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('workspace_sequence',
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('workspace_id')
    )
    op.create_table('hof_node_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('retries_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['hof_flow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hof_node_states_execution_id'), 'hof_node_states', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hof_node_states_execution_id'), table_name='hof_node_states')
    op.drop_table('hof_node_states')
    op.drop_table('workspaces')
    op.drop_table('workspace_sequence')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_table('users')
    op.drop_index(op.f('ix_read_markers_user_id'), table_name='read_markers')
    op.drop_index(op.f('ix_read_markers_channel_id'), table_name='read_markers')
    op.drop_table('read_markers')
    op.drop_index(op.f('ix_reactions_message_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_proposals_workspace_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_channel_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_pinned_channel_id'), table_name='pinned')
    op.drop_table('pinned')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_thread_root'), table_name='messages')
    op.drop_index(op.f('ix_messages_sequence'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_hof_flow_executions_status'), table_name='hof_flow_executions')
    op.drop_index(op.f('ix_hof_flow_executions_flow_name'), table_name='hof_flow_executions')
    op.drop_table('hof_flow_executions')
    op.drop_index(op.f('ix_events_workspace_id'), table_name='events')
    op.drop_index(op.f('ix_events_sequence'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_drafts_user_id'), table_name='drafts')
    op.drop_index(op.f('ix_drafts_channel_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_channels_workspace_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_channel_members_user_id'), table_name='channel_members')
    op.drop_index(op.f('ix_channel_members_channel_id'), table_name='channel_members')
    op.drop_table('channel_members')
    op.drop_index(op.f('ix_attachments_workspace_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_agents_workspace_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
